channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.5
  - pip
  - Pillow==8.3.1
  - tensorflow==2.7.0
  - keras==2.7.0
  - pandas==1.3.4
  - scikit-learn==1.0.1
  - numpy==1.21.0
  - streamlit==0.85.1

  - pip:
    - 
    - streamlit-authenticator==0.0.5
    - silence_tensorflow
